export enum DBTable{
    AUTHORS = "authors",
    BOOKS = "books",
    USERS = "users",
    AGENDAMENTOS = "agendamentos",
    CLIENTES = "clientes",
    FUNCIONARIOS = "funcionarios",
    HORARIOS = "horarios",
    NOTIFICACOES = "notificacoes",
    PAGAMENTOS = "pagamentos",
    FUNCIONARIO_HORARIO = "funcionario_horario",
    SERVICOS = "servicos",
    CATEGORIAS = "categorias",
    PRODUTOS = "produtos",
    FORNECEDORES = "fornecedores",
    EQUIPAMENTOS = "equipamentos",
    ATENDIMENTOS = "atendimentos",
    FEEDBACKS = "feedbacks"
}